# Generated by Django 5.2.8 on 2025-12-23 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_questiondislike'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='dislikes',
            field=models.ManyToManyField(related_name='question_dislikes', through='app.QuestionDislike', to='app.profile'),
        ),
    ]
